### Health Check
GET http://localhost:8082/api/health-check-http
Accept: application/json


### Register User (Email)
POST http://localhost:8082/api/auth/register-email
Content-Type: application/json
Accept: application/json

{
  "name": "John",
  "email": "johdn@example.com",
  "password": "password123"
}

### Login User (Email)
POST http://localhost:8082/api/auth/login-email
Content-Type: application/json
Accept: application/json
X-Platform: web

{
  "email": "johdn@example.com",
  "password": "password123"
}

### Logout
POST http://localhost:8082/api/auth/logout
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJuYW1lIjoiSm9obiIsIlgtUGxhdGZvcm0iOiJ3ZWIiLCJzdWIiOiIyIiwiZXhwIjoxNzc4MjQ1Njk2fQ.ZIJUsTyS-KT2am9ejU91CW0fT80azR7IWMue0oluSZI
X-Platform: web
