### Health Check
GET http://localhost:8082/api/health-check-http
Accept: application/json


### Register User (Email)
POST http://localhost:8082/api/auth/register-email
Content-Type: application/json
Accept: application/json

{
  "name": "John",
  "email": "johdn@example.com",
  "password": "password123"
}

### Login User (Email)
POST http://localhost:8082/api/auth/login-email
Content-Type: application/json
Accept: application/json
X-Platform: web

{
  "email": "johdn@example.com",
  "password": "password123"
}

### Logout
POST http://localhost:8082/api/auth/logout
Accept: application/json
Authorization: Bearer <access_token>
X-Platform: web


### Refresh Session
POST http://localhost:8082/api/auth/refresh-session
Accept: application/json
Content-Type: application/json
X-Platform: web

{
  "refreshToken": "<refresh_token>"
}